### ISSUE TITLE
"Rewind" should be "Next"

### ISSUE THREAD

**Issue by ajrominger** [role-model/roleShiny#2]
Sorry for the confusion in the mockup!  The button currently designated "rewind" should actually be a "step" or "next" button, i.e., it should advance the simulation by one step.  Probably that means we should also use a more intuitive button symbol.  Again, that was my bad for putting what looked like a rewind symbol in the mockup.

**Comment by rafelafrance** [comment]
It's a next track symbol which may not be appropriate here.

**Comment by ajrominger** [comment]
that works for me! we can re-open if others feel differently. thanks!
